#!/bin/sh
# Merge deepseek-ai/deepseek-harness `master` into this fork's `master`.
#
# `master` carries local commits (the plugin-facing session-event write side,
# the Trajectory extension row, and their docs), so this can never fast-forward
# and a conflict is possible whenever upstream edits the same regions.
#
# A conflict inside a generated document resolves itself. Every generated file
# names its generator in its own header, so that generator is re-run over the
# merged tree and its `verify-<name>` gate must accept the result. Regenerating
# is the only answer that holds for both sides: the generated content is a
# function of the merged tree, which neither the local nor the upstream copy is.
#
# Everything else aborts the merge and leaves the branch exactly as it was: a
# conflicted file no generator owns, a conflicted region that re-running the
# generator does not rewrite (authored prose in a hybrid document), a generator
# that fails, and a freshness gate that rejects the result. Resolve those by
# hand and run the script again.
#
# Needs the `origin` (this fork) and `upstream` (deepseek-ai) remotes, and an
# installed workspace (`pnpm install`) whenever a document has to be rebuilt.
set -eu

BRANCH=master

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo 'sync-upstream: tracked files have uncommitted changes; commit or stash them first' >&2
  exit 1
fi

git fetch --no-tags upstream "$BRANCH"
git fetch --no-tags origin "$BRANCH"
git checkout "$BRANCH"

# Upstream is already in, but the push that publishes it may still be owed: an
# earlier run can have merged and then failed to push.
if git merge-base --is-ancestor "upstream/$BRANCH" HEAD; then
  if git merge-base --is-ancestor HEAD "origin/$BRANCH"; then
    echo "sync-upstream: $BRANCH already contains upstream/$BRANCH"
    exit 0
  fi
  git push origin "$BRANCH"
  echo "sync-upstream: $BRANCH now contains upstream/$BRANCH"
  exit 0
fi

BEFORE=$(git rev-parse HEAD)
CONFLICTS=$(mktemp)
GENERATORS=$(mktemp)
trap 'rm -f "$CONFLICTS" "$GENERATORS"' EXIT

# Leave the branch as the caller had it, whichever way this run ends.
undo() {
  if git rev-parse -q --verify MERGE_HEAD >/dev/null 2>&1; then
    git merge --abort
  fi
  git reset --hard "$BEFORE" >/dev/null
}
abort() {
  undo
  echo "sync-upstream: $1; $BRANCH is unchanged" >&2
  exit 1
}

# The generator one conflicted file names in its header, or nothing. That header
# is what makes a file regenerable at all, so a file without one is a conflict
# this script cannot answer.
generator_of() {
  git show ":3:$1" 2>/dev/null \
    | sed -n '1,10{s|.*scripts/\(gen-[A-Za-z0-9._-]*\)\.ts.*|\1|p;}' \
    | head -n 1
}

if git merge --no-edit "upstream/$BRANCH"; then
  git push origin "$BRANCH"
  echo "sync-upstream: $BRANCH now contains upstream/$BRANCH"
  exit 0
fi

git diff --name-only --diff-filter=U > "$CONFLICTS"
[ -s "$CONFLICTS" ] || abort "the merge stopped without unmerged paths (see git's own output above)"

while IFS= read -r path; do
  name=$(generator_of "$path")
  [ -n "$name" ] || abort "upstream/$BRANCH conflicts with the local commits on $BRANCH in $path, which no generator owns"
  echo "sync-upstream: $path is generated by scripts/$name.ts"
  printf '%s\n' "$name" >> "$GENERATORS"
done < "$CONFLICTS"

for name in $(sort -u "$GENERATORS"); do
  echo "sync-upstream: regenerating with pnpm run $name"
  pnpm run "$name" || abort "pnpm run $name failed, so the documents it owns could not be rebuilt (is the workspace installed?)"
done

# The generator's own freshness gate is what accepts the rebuilt documents; a
# generator without one falls through to the marker check below.
for name in $(sort -u "$GENERATORS"); do
  gate="verify-$(printf '%s' "$name" | sed 's/^gen-//')"
  if grep -q "\"$gate\":" package.json; then
    pnpm run "$gate" || abort "pnpm run $gate rejected the rebuilt documents"
  fi
done

# A conflict the generators do not own survives regeneration as markers: that is
# a hand edit to a document rebuilt from source, and it needs a human.
while IFS= read -r path; do
  if grep -q '^<<<<<<< ' "$path" 2>/dev/null; then
    abort "conflict markers remain in $path, which re-running its generator does not rewrite"
  fi
done < "$CONFLICTS"

# Tracked paths only: this checkout may carry untracked local work (plugins, a
# local preset) that no part of this sync owns.
git add -u
git commit --no-edit
git push origin "$BRANCH"
echo "sync-upstream: $BRANCH now contains upstream/$BRANCH, with generated-document conflicts resolved by regeneration"
